#!/usr/bin/env bash
# Canonical : https://github.com/lduran2/git-unzip-all/git-config-pre-commit
# Configure the pre-commit hook to run hooks/unzip-all.
# By        : Leomar Duran <https://github.com/lduran2>
# When      : 2022-01-25t22:32R
# Version   : 1.1.4
# 
# CHANGELOG :
#   v1.1.4 - 2022-01-25t22:42R
#       add variable references in strings
#
#   v1.1.3 - 2022-01-25t22:32R
#       added `SCRIPT_ROOT` for files rel to script
#
#   v1.1.2 - 2022-01-25t22:24R
#       fixed the unformated strings for the life cycle messages
#
#   v1.1.1 - 2022-01-25t22:16R
#       fixed the template strings for the config filenames
#
#   v1.1.0 - 2022-01-25t22:02R
#       sets up the pattern file
#       reconfigured for submodule
#
#   v1.0.0 - 2022-01-25t19:39R
#       composes the hook file for pre-commit
#

# the path of the script root
declare -r SCRIPT_ROOT="${BASH_SOURCE%/*}/"
# the path of the repo root
declare -r REPO_ROOT="$SCRIPT_ROOT../../"
# hook file to which to attach
declare -r HOOK_FILE="$REPO_ROOT.git/hooks/pre-commit"
# contains the patterns of files to unzip
declare -r PATTERN_FILE="$REPO_ROOT.unzip"

# if the file does not exist
if [[ ! -f "$HOOK_FILE" ]] ;
then
	echo 'Created the pre-commit hook file.'
	# start it by adding the head
	cat < "$SCRIPT_ROOT./templates/header" > "$HOOK_FILE"
fi # [[ ! -f "$HOOK_FILE" ]]

echo 'Added `unzip-all` to the pre-commit hook file.'
# always add the hook that attaches `. hooks/unzip-all`
cat < "$SCRIPT_ROOT./templates/body-source" >> "$HOOK_FILE"

# if the pattern file does not exist
if [[ ! -f "$PATTERN_FILE" ]] ;
then
	echo 'Create the pattern file `/.unzip`'
	# copy it from the template
	cat < "$SCRIPT_ROOT./templates/.unzip" > "$PATTERN_FILE"
fi # [[ ! -f "$PATTERN_FILE" ]]

# confirm finished
echo 'Done.'
