#!/usr/bin/env bash
# Canonical : https://github.com/lduran2/git-unzip-all/main
# Decompresses all Simulink models in this repo after pushing to
# remote.
# By        : Leomar Duran <https://github.com/lduran2>
# When      : 2022-01-01t10:14R
# Version   : 1.3.1
# 
# CHANGELOG :
#   v1.3.1 - 2022-02-01t10:14R
#       patch `ROOTDIR` -> `ROOT_DIR`
#
#   v1.3.0 - 2022-02-01t05:18R
#       use `dirname` to hangle resource locality
#
#   v1.2.2 - 2022-01-25t22:07R
#       now assumed to be in `hooks/unzip-all`
#       reconfigured for submodule
#
#   v1.2.1 - 2022-01-25t20:02R
#       nonverbose unzip bcs the files were not being unzipped
#
#   v1.2.0 - 2022-01-25t06:40R
#       trim spaces from patterns; root constant, progress message,
#           verbose unzip
#
#   v1.1.0 - 2022-01-24t04:51R
#       decompresses any file matching patterns from "../.unzip"
#
#   v1.0.0 - 2022-01-24t04:51R
#       decompresses all Simulink models
#

# working directories
declare -r SOURCE_DIR=$(dirname $0)
declare -r ROOT_DIR="$SOURCE_DIR/../.."

# configuration file contains the file patterns to unzip
declare -r PATTERN_FILE="$ROOT_DIR/.unzip"

# read all lines from the configuration file
while read SPACE_PATTERN ; do
	# remove surrounding spaces
	pattern=$(echo "$SPACE_PATTERN" | xargs)
	# if the link is not a comment, accept it as a file pattern
	if [[ "$pattern" != \#* ]] ;
	then
		echo "unzipping files matching \"${pattern%/\r}\" . . ."
		# find each file matching the pattern
		find "$ROOT_DIR/" -type f -name "$pattern" -printf '%p\n' |
			# read the filename into FILE
			while read FILE ; do
				echo "unzipping file \"$FILE\" . . ."
				# unzip to a directory with the same name
				# sans extension, overwriting any files therein
				unzip_dir="${FILE%.*}"
				unzip -o "$FILE" -d "$unzip_dir"
				# unadd the file from commit
				git reset HEAD "$FILE"
				# add the zipped directory
				git add "$unzip_dir"
			done # while read FILE
		# done find FILE
	fi # [[ "$pattern" != \#* ]]; then
done < "$PATTERN_FILE" # while read SPACE_PATTERN

# confirm finished
echo "Done."
